project:
  type: website

website:
  title: "lazappi"
  navbar:
    left:
      - posts/index.qmd
      - projects/index.qmd
      - talks/index.qmd
      - publications/index.qmd
    right:
      - icon: github
        href: https://github.com/lazappi
      - icon: twitter
        href: https://twitter.com/_lazappi_
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
