project:
  type: website

website:
  title: "lazappi"
  site-url: https://lazappi.id.au
  description: "Luke Zappia's personal website"
  favicon: icon.png
  navbar:
    left:
      - posts/index.qmd
      - projects/index.qmd
      - talks/index.qmd
      - publications/index.qmd
    right:
      - icon: github
        href: https://github.com/lazappi
      - icon: rss
        href: posts/index.xml
  page-footer:
    left:
      - text: "© 2016-2025, Luke Zappia"
    right:
      - text: "License"
        href: license.qmd
  twitter-card:
    creator: "@_lazappi_"
    site: "@_lazappi_"
  open-graph:
    locale: en_AU
    site-name: lazappi
  cookie-consent:
    palette: dark
  google-analytics:
    tracking-id: "G-20JH368VMR"
    anonymize-ip: true
header-includes: |
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Code&family=Rubik&display=swap" rel="stylesheet">
format:
  html:
    theme:
      light: [flatly, css/custom.scss]
      dark: [darkly, css/custom.scss, css/dark.scss]
    mainfont: "Rubik"
    monofont: "Fira Code"

editor: visual
