project:
  type: website

website:
  title: "quarto-blog"
  navbar:
    left:
      - posts.qmd
      - projects.qmd
      - talks.qmd
      - publications.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
